### PR TITLE
add: link to replit run

### PR DESCRIPTION
**Pull request by eankeen**
i think it would be pretty cool to let people see how this code works (and edit / preview the program) right in their browser, without any manual downloads or installation. i'm thinking we can add a 'run on repl.it' button, which redirects to something like [this](https://repl.it/@eankeen/run-terminal-kit):

image

### CODE REVIEW

**Comment by cronvel** [comment]
Hi @eankeen 
It could be nice, but do you know how to configure this service properly?
I just tried it, and it appears that I have to type npm install before being able to launch the various script located in *./sample/*.
I'm a bit busy so I can't play with the service at the moment, if you could give me some pointer, I would gladly merge your PR.

**Comment by eankeen** [comment]
hmm, that's kind of odd because the packages were supposed to be installed. i played with it a bit more and it appears that the the symlink in the `node_modules` folder appears to be missing. i can fix it by adding `yarn link` commands in the `.replit` file. (using `npm link` yields permission denied errors)

**Comment by cronvel** [comment]
@eankeen The link in `sample/node_modules` exists because I wanted that the scripts ending with *-doc.js* to be exactly like those in the documentation, hence requiring with a `require( 'terminal-kit' )` instead of `require( '..' )`. But other scripts does not run too. It appears that the top-level directory `npm install` does not work, it is just as if the *run* command in `.replit` was never executed (I'm currently testing things on my side, with no more luck than you).

**Comment by cronvel** [comment]
@eankeen Aaaaah sorry... I forgot to click the "run" button lol ^^
Since I got terminal+bash ready, I was assuming that installation was already done behind the scene...

**Comment by cronvel** [comment]
Ok it works now... Thanks a lot! ;)

**Pull request closed without merging**
